### ISSUE TITLE
headless services get prefixed hostname

### ISSUE THREAD

**Issue by an-tex** [jaredallard/localizer#36]
a headless service like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: mynamespace
spec:
  # this is the important part
  clusterIP: None
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: 9042
  publishNotReadyAddresses: true
  selector:
    app: cassandracluster
  type: ClusterIP
```

gets exposed through (and it's shorter non-fqdn aliases):

`cassandra-0.cassandra.mynamespace.svc.cluster.local`

even though it should be just 

`cassandra.mynamespace.svc.cluster.local`

headless services are described [here](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).
